### PR TITLE
[85]:Develop RESTful API for Institute Management System.

### PR DESCRIPTION
**Pull request by BaraahAlKalbani**

### CODE REVIEW

**Review by AnwaarAlbusaidi — APPROVED** [review]
well Done

**Comment by Najlaalrajhia98** [comment]
Great Work!

**Review by Najlaalrajhia98 — APPROVED** [review]

**Review by CodelineAtyab — APPROVED** [review]
Approve

**Review by RoqayaAlmamari — APPROVED** [review]
Awesome

**Pull request closed without merging**
